{{- $root := . -}}
{{- range $deploy, $deployValue := .Values.deployments }}
{{- if $deployValue.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" $root }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" $root }}
    app.kubernetes.io/instance: {{ $deploy }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" $root }}
  minReplicas: {{ $deployValue.autoscaling.minReplicas }}
  maxReplicas: {{ $deployValue.autoscaling.maxReplicas }}
  metrics:
    {{- if $deployValue.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $deployValue.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $deployValue.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $deployValue.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}