---
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-env
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "9"
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
kind: Secret
type: Opaque
data:
  {{- range $key, $value := .Values.secret_env_variables }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

