{{- $root := . -}}
{{- range $service, $serviceValue := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" $root }}-{{ $service }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" $root }}
    app.kubernetes.io/instance: {{ $service }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  type: {{ $serviceValue.type }}
  ports:
  {{- range $portName, $portValues := $serviceValue.ports }}
    - name: {{ $portName }}
      port: {{ $portValues.servicePort }}
      targetPort: {{ $portValues.targetPort }}
      protocol: {{ $portValues.protocol }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "chart.name" $root }}
    app.kubernetes.io/instance: {{ $service }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
{{- end }}
